name: Java CI with SpotBugs

on:
  push: {}
  pull_request: {}

jobs:
  spotbugs-check:
    name: SpotBugs Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'liberica'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Run SpotBugs with Gradle
        run: ./gradlew clean spotbugsMain

      - name: Upload SpotBugs report
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-report
          path: build/reports/spotbugs/
          if-no-files-found: warn