name: Java CI with SpotBugs

on:
  push: {}
  pull_request: {}

jobs:
  spotbugs-check:
    name: SpotBugs Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'liberica'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Run SpotBugs with Gradle
        run: ./gradlew clean spotbugsMain

      - name: Upload SpotBugs report
        uses: actions/upload-pages-artifact@v4
        with:
          path: build/reports/spotbugs/spotbugs.html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4